import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/home/Navbar";

import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/context/AuthContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <AuthProvider>
        <div>
          <Navbar/>
        </div>
        <Toaster/>
        {children}
        <div className="fixed bottom-1 w-full mt-20 p-2">
        {/* <BottomBar /> */}
      </div>
      </AuthProvider>
      </body>
    </html>
  );
}
